/**
 * lib/engine/worlds.ts
 *
 * Definición completa de los mundos de RitmoLab.
 * Este archivo es la tabla de contenidos principal del motor pedagógico.
 */

import type { WorldDef, WorldId } from "./types";
import { DOMAIN_CRITERIA } from "./types";

export const WORLDS: Record<WorldId, WorldDef> = {
  pulse: {
    id: "pulse",
    title: "Mundo 1: Pulso interno",
    description: "La base de todo: sentir el pulso estable antes de leer figuras.",
    color: "bg-brand-500",
    emoji: "🥁",
    primarySkill: "pulse",
    skills: ["pulse", "silence"],
    figures: ["quarter", "quarter_rest"],
    timeSignatures: ["4/4"],
    reading: [],
    bpmRange: { min: 60, max: 90 },
    difficulty: 1,
    anchorLessonSlugs: ["pulso-y-negra", "silencios-basicos", "corcheas"],
    generativeExercisesPerSession: 4,
    domainCriteria: DOMAIN_CRITERIA.strong,
  },

  durations: {
    id: "durations",
    title: "Mundo 2: Duraciones",
    description: "Blanca y redonda: sentir que un sonido puede durar más de un pulso.",
    color: "bg-teal-500",
    emoji: "🎵",
    primarySkill: "reading",
    skills: ["pulse", "reading"],
    figures: ["whole", "half", "quarter", "half_rest", "quarter_rest"],
    timeSignatures: ["4/4"],
    reading: [],
    bpmRange: { min: 60, max: 85 },
    difficulty: 1,
    prerequisiteWorld: "pulse",
    anchorLessonSlugs: ["blanca-intro", "redonda-intro", "duraciones-mixtas"],
    generativeExercisesPerSession: 4,
    domainCriteria: DOMAIN_CRITERIA.strong,
  },

  eighths: {
    id: "eighths",
    title: "Mundo 3: Corcheas y subdivisión inicial",
    description: "Corcheas, patrones mixtos y compás 4/4 en profundidad.",
    color: "bg-sky-500",
    emoji: "🎼",
    primarySkill: "reading",
    skills: ["reading", "subdivision", "pulse"],
    figures: ["quarter", "eighth", "quarter_rest", "eighth_rest"],
    timeSignatures: ["4/4"],
    reading: [],
    bpmRange: { min: 70, max: 100 },
    difficulty: 3,
    prerequisiteWorld: "durations",
    anchorLessonSlugs: ["negras-corcheas", "compas-cuatro-cuatro"],
    generativeExercisesPerSession: 5,
    domainCriteria: DOMAIN_CRITERIA.strong,
  },

  reading: {
    id: "reading",
    title: "Mundo 4: Lectura rítmica",
    description:
      "Convertí las figuras escritas en ritmo real: leer, contar y ejecutar sin perder el pulso.",
    color: "bg-blue-500",
    emoji: "📖",
    primarySkill: "reading",
    skills: ["reading", "pulse"],
    figures: ["quarter", "quarter_rest", "eighth"],
    timeSignatures: ["4/4"],
    reading: [],
    bpmRange: { min: 60, max: 100 },
    difficulty: 4,
    prerequisiteWorld: "eighths",
    anchorLessonSlugs: ["lectura-con-metronomo", "dictado-simple"],
    generativeExercisesPerSession: 4,
    domainCriteria: DOMAIN_CRITERIA.strong,
  },

  dictation: {
    id: "dictation",
    title: "Mundo 5: Oído rítmico",
    description: "Escuchá ritmos y elegí la partitura correcta.",
    color: "bg-yellow-400",
    emoji: "👂",
    primarySkill: "dictation",
    skills: ["dictation", "reading"],
    figures: ["quarter", "eighth", "quarter_rest"],
    timeSignatures: ["4/4"],
    reading: [],
    bpmRange: { min: 72, max: 90 },
    difficulty: 3,
    prerequisiteWorld: "reading",
    anchorLessonSlugs: ["dictado-simple"],
    generativeExercisesPerSession: 6,
    domainCriteria: DOMAIN_CRITERIA.strong,
  },

  subdivision: {
    id: "subdivision",
    title: "Mundo 6: Subdivisión",
    description: "Tresillos, semicorcheas y coordinación vocal-corporal.",
    color: "bg-purple-500",
    emoji: "✂️",
    primarySkill: "subdivision",
    skills: ["subdivision", "reading", "dictation"],
    figures: ["quarter", "eighth", "triplet", "sixteenth"],
    timeSignatures: ["4/4"],
    reading: [],
    bpmRange: { min: 60, max: 88 },
    difficulty: 5,
    prerequisiteWorld: "dictation",
    anchorLessonSlugs: ["tresillos-intro", "semicorcheas-intro"],
    generativeExercisesPerSession: 5,
    domainCriteria: DOMAIN_CRITERIA.strong,
  },

  musicalidad: {
    id: "musicalidad",
    title: "Mundo 7: Groove y compás",
    description: "Síncopa, compás compuesto y patrones aplicados.",
    color: "bg-red-500",
    emoji: "⚡",
    primarySkill: "syncopation",
    skills: ["syncopation", "meter", "groove"],
    figures: ["quarter", "eighth", "syncope", "dotted_quarter"],
    timeSignatures: ["4/4", "6/8"],
    reading: [],
    bpmRange: { min: 70, max: 100 },
    difficulty: 6,
    prerequisiteWorld: "subdivision",
    anchorLessonSlugs: ["sincopa-intro", "compas-seis-ocho"],
    generativeExercisesPerSession: 5,
    domainCriteria: DOMAIN_CRITERIA.strong,
  },

  memory: {
    id: "memory",
    title: "Mundo 8: Memoria rítmica",
    description: "Escuchás, retenés y reproducís: el músico real.",
    color: "bg-purple-600",
    emoji: "🧠",
    primarySkill: "memory",
    skills: ["memory", "dictation", "pulse"],
    figures: ["quarter", "eighth", "quarter_rest"],
    timeSignatures: ["4/4"],
    reading: [],
    bpmRange: { min: 68, max: 88 },
    difficulty: 5,
    prerequisiteWorld: "dictation",
    anchorLessonSlugs: [
      "memoria-ritmica-intro",
      "call-response-basico",
      "call-response-corcheas",
    ],
    generativeExercisesPerSession: 4,
    domainCriteria: DOMAIN_CRITERIA.strong,
  },

  advanced: {
    id: "advanced",
    title: "Mundo 9: Desafíos integrales",
    description: "Lectura, oído y metrónomo bajo presión real.",
    color: "bg-zinc-900",
    emoji: "🏆",
    primarySkill: "sight_reading",
    skills: ["pulse", "reading", "dictation", "subdivision", "memory"],
    figures: ["quarter", "eighth", "triplet", "syncope", "dotted_quarter"],
    timeSignatures: ["4/4", "3/4"],
    reading: [],
    bpmRange: { min: 80, max: 110 },
    difficulty: 8,
    prerequisiteWorld: "musicalidad",
    anchorLessonSlugs: ["lectura-con-metronomo", "examen-final-ritmico"],
    generativeExercisesPerSession: 6,
    domainCriteria: DOMAIN_CRITERIA.mastered,
  },

  speed: {
    id: "speed",
    title: "Mundo 10: Velocidad progresiva",
    description:
      "El mismo patrón, el BPM sube. Hasta dónde llegás manteniendo precisión.",
    color: "bg-orange-500",
    emoji: "🚀",
    primarySkill: "speed",
    skills: ["speed", "pulse", "reading"],
    figures: ["quarter", "eighth", "dotted_quarter"],
    timeSignatures: ["4/4"],
    reading: [],
    bpmRange: { min: 80, max: 160 },
    difficulty: 6,
    prerequisiteWorld: "advanced",
    anchorLessonSlugs: [],
    generativeExercisesPerSession: 5,
    domainCriteria: DOMAIN_CRITERIA.mastered,
  },

  latin: {
    id: "latin",
    title: "Mundo 11: Ritmos latinoamericanos",
    description: "Bossa nova, tango, clave afrocubana. Groove con identidad.",
    color: "bg-yellow-500",
    emoji: "🌶️",
    primarySkill: "groove",
    skills: ["groove", "syncopation", "meter"],
    figures: ["quarter", "eighth", "dotted_quarter", "syncope"],
    timeSignatures: ["4/4", "2/4"],
    reading: [],
    bpmRange: { min: 80, max: 130 },
    difficulty: 7,
    prerequisiteWorld: "musicalidad",
    anchorLessonSlugs: [],
    generativeExercisesPerSession: 5,
    domainCriteria: DOMAIN_CRITERIA.mastered,
  },

  jazz: {
    id: "jazz",
    title: "Mundo 12: Jazz y swing",
    description: "Corcheas de swing, tresillos en contexto y el feel del jazz.",
    color: "bg-blue-800",
    emoji: "🎷",
    primarySkill: "groove",
    skills: ["groove", "subdivision", "syncopation"],
    figures: ["quarter", "eighth", "triplet", "eighth_triplet", "syncope"],
    timeSignatures: ["4/4"],
    reading: [],
    bpmRange: { min: 90, max: 160 },
    difficulty: 7,
    prerequisiteWorld: "subdivision",
    anchorLessonSlugs: [],
    generativeExercisesPerSession: 5,
    domainCriteria: DOMAIN_CRITERIA.mastered,
  },

  sight: {
    id: "sight",
    title: "Mundo 13: Lectura a primera vista",
    description: "Patrones nuevos cada vez. Nunca el mismo ejercicio dos veces.",
    color: "bg-green-700",
    emoji: "👁️",
    primarySkill: "sight_reading",
    skills: ["sight_reading", "reading", "pulse"],
    figures: [
      "quarter",
      "eighth",
      "dotted_quarter",
      "triplet",
      "quarter_rest",
      "eighth_rest",
    ],
    timeSignatures: ["4/4", "3/4", "2/4"],
    reading: [],
    bpmRange: { min: 70, max: 110 },
    difficulty: 7,
    prerequisiteWorld: "advanced",
    anchorLessonSlugs: [],
    generativeExercisesPerSession: 8,
    domainCriteria: DOMAIN_CRITERIA.mastered,
  },

  meters: {
    id: "meters",
    title: "Mundo 14: Compases irregulares",
    description: "5/4, 7/8 y otros compases que rompen la simetría binaria.",
    color: "bg-indigo-600",
    emoji: "📐",
    primarySkill: "meter",
    skills: ["meter", "pulse", "reading"],
    figures: ["quarter", "eighth", "dotted_quarter"],
    timeSignatures: ["5/4", "7/8", "3/4"],
    reading: [],
    bpmRange: { min: 70, max: 110 },
    difficulty: 9,
    prerequisiteWorld: "musicalidad",
    anchorLessonSlugs: [],
    generativeExercisesPerSession: 4,
    domainCriteria: DOMAIN_CRITERIA.mastered,
  },

  funk: {
    id: "funk",
    title: "Mundo 15: Funk y groove",
    description: "El 16º como unidad, síncopa cruzada y el piso inamovible.",
    color: "bg-pink-600",
    emoji: "🎸",
    primarySkill: "groove",
    skills: ["groove", "subdivision", "syncopation", "independence"],
    figures: ["sixteenth", "eighth", "syncope", "dotted_quarter"],
    timeSignatures: ["4/4"],
    reading: [],
    bpmRange: { min: 80, max: 130 },
    difficulty: 8,
    prerequisiteWorld: "subdivision",
    anchorLessonSlugs: [],
    generativeExercisesPerSession: 5,
    domainCriteria: DOMAIN_CRITERIA.mastered,
  },

  master: {
    id: "master",
    title: "Mundo 16: Modo maestro",
    description:
      "Retos de precisión máxima. Para los que dominaron todo lo anterior.",
    color: "bg-zinc-950",
    emoji: "🌟",
    primarySkill: "sight_reading",
    skills: [
      "pulse",
      "reading",
      "dictation",
      "subdivision",
      "memory",
      "speed",
      "groove",
    ],
    figures: [
      "whole",
      "half",
      "quarter",
      "eighth",
      "sixteenth",
      "triplet",
      "dotted_quarter",
      "syncope",
      "eighth_triplet",
    ],
    timeSignatures: ["4/4", "3/4", "6/8", "5/4"],
    reading: [],
    bpmRange: { min: 100, max: 180 },
    difficulty: 10,
    prerequisiteWorld: "advanced",
    anchorLessonSlugs: [],
    generativeExercisesPerSession: 8,
    domainCriteria: DOMAIN_CRITERIA.mastered,
  },
};

export const WORLD_ORDER: WorldId[] = [
  "pulse",
  "durations",
  "eighths",
  "reading",
  "dictation",
  "subdivision",
  "musicalidad",
  "memory",
  "advanced",
  "speed",
  "latin",
  "jazz",
  "sight",
  "meters",
  "funk",
  "master",
];

export function getWorld(id: WorldId): WorldDef {
  return WORLDS[id];
}

export function getNextWorld(currentId: WorldId): WorldDef | null {
  const idx = WORLD_ORDER.indexOf(currentId);

  if (idx < 0 || idx >= WORLD_ORDER.length - 1) {
    return null;
  }

  return WORLDS[WORLD_ORDER[idx + 1]];
}